// User seed data organized by role
export const usersData = [
  // Administrators
  {
    email: 'admin@git.edu.gh',
    firstName: 'John',
    lastName: 'Administrator',
    middleName: 'Kwame',
    title: 'Dr',
    role: 'ADMIN',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-0001',
    dateOfBirth: new Date('1975-03-15'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '123 Admin Avenue, East Legon, Accra',
    facultyCode: null, // Institution level
    departmentCode: null
  },

  // Faculty Admins (Deans)
  {
    email: 'dean.engineering@git.edu.gh',
    firstName: 'Mary',
    lastName: 'Engineering-Dean',
    middleName: 'Akosua',
    title: 'Prof',
    role: 'FACULTY_ADMIN',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-0101',
    dateOfBirth: new Date('1970-07-20'),
    gender: 'Female',
    nationality: 'Ghanaian',
    address: '456 Faculty Street, Accra',
    facultyCode: 'ENG',
    departmentCode: null
  },
  {
    email: 'dean.science@git.edu.gh',
    firstName: 'Robert',
    lastName: 'Science-Dean',
    middleName: 'Kofi',
    title: 'Prof',
    role: 'FACULTY_ADMIN',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-0102',
    dateOfBirth: new Date('1968-11-05'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '789 Science Road, Accra',
    facultyCode: 'SCI',
    departmentCode: null
  },

  // Heads of Department
  {
    email: 'hod.cse@git.edu.gh',
    firstName: 'Sarah',
    lastName: 'CS-Head',
    middleName: 'Ama',
    title: 'Dr',
    role: 'HOD',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-0201',
    dateOfBirth: new Date('1978-09-12'),
    gender: 'Female',
    nationality: 'Ghanaian',
    address: '321 Tech Boulevard, Accra',
    facultyCode: 'ENG',
    departmentCode: 'CSE'
  },
  {
    email: 'hod.math@git.edu.gh',
    firstName: 'David',
    lastName: 'Math-Head',
    middleName: 'Kwaku',
    title: 'Dr',
    role: 'HOD',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-0301',
    dateOfBirth: new Date('1972-04-18'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '654 Mathematics Lane, Accra',
    facultyCode: 'SCI',
    departmentCode: 'MATH'
  },

  // Exams Officers
  {
    email: 'exams.engineering@git.edu.gh',
    firstName: 'Grace',
    lastName: 'Exams-Officer',
    middleName: 'Adjoa',
    title: 'Mrs',
    role: 'EXAMS_OFFICER',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-0401',
    dateOfBirth: new Date('1980-06-25'),
    gender: 'Female',
    nationality: 'Ghanaian',
    address: '987 Exams Street, Accra',
    facultyCode: 'ENG',
    departmentCode: null
  },
  {
    email: 'exams.science@git.edu.gh',
    firstName: 'Michael',
    lastName: 'Exams-Officer',
    middleName: 'Yaw',
    title: 'Mr',
    role: 'EXAMS_OFFICER',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-0402',
    dateOfBirth: new Date('1982-01-10'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '147 Assessment Avenue, Accra',
    facultyCode: 'SCI',
    departmentCode: null
  },

  // Lecturers - Computer Science
  {
    email: 'james.lecturer@git.edu.gh',
    firstName: 'James',
    lastName: 'Mensah',
    middleName: 'Kwame',
    title: 'Dr',
    role: 'LECTURER',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-1001',
    dateOfBirth: new Date('1985-03-14'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '258 Lecturer Lane, Accra',
    facultyCode: 'ENG',
    departmentCode: 'CSE'
  },
  {
    email: 'jennifer.lecturer@git.edu.gh',
    firstName: 'Jennifer',
    lastName: 'Asante',
    middleName: 'Akosua',
    title: 'Dr',
    role: 'LECTURER',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-1002',
    dateOfBirth: new Date('1983-08-22'),
    gender: 'Female',
    nationality: 'Ghanaian',
    address: '369 Academic Road, Accra',
    facultyCode: 'ENG',
    departmentCode: 'CSE'
  },
  {
    email: 'peter.lecturer@git.edu.gh',
    firstName: 'Peter',
    lastName: 'Osei',
    middleName: 'Kofi',
    title: 'Dr',
    role: 'LECTURER',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-1003',
    dateOfBirth: new Date('1979-12-05'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '741 Faculty Drive, Accra',
    facultyCode: 'ENG',
    departmentCode: 'CSE'
  },

  // Lecturers - Mathematics
  {
    email: 'elizabeth.lecturer@git.edu.gh',
    firstName: 'Elizabeth',
    lastName: 'Opoku',
    middleName: 'Ama',
    title: 'Dr',
    role: 'LECTURER',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-1101',
    dateOfBirth: new Date('1981-05-30'),
    gender: 'Female',
    nationality: 'Ghanaian',
    address: '852 Math Street, Accra',
    facultyCode: 'SCI',
    departmentCode: 'MATH'
  },
  {
    email: 'samuel.lecturer@git.edu.gh',
    firstName: 'Samuel',
    lastName: 'Adjei',
    middleName: 'Kwaku',
    title: 'Dr',
    role: 'LECTURER',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-1102',
    dateOfBirth: new Date('1977-10-15'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '963 Statistics Avenue, Accra',
    facultyCode: 'SCI',
    departmentCode: 'MATH'
  },

  // Lecturers - Physics
  {
    email: 'rachel.lecturer@git.edu.gh',
    firstName: 'Rachel',
    lastName: 'Boateng',
    middleName: 'Adjoa',
    title: 'Dr',
    role: 'LECTURER',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-1201',
    dateOfBirth: new Date('1984-02-28'),
    gender: 'Female',
    nationality: 'Ghanaian',
    address: '159 Physics Place, Accra',
    facultyCode: 'SCI',
    departmentCode: 'PHYS'
  },

  // Lecturers - Electrical Engineering
  {
    email: 'frank.lecturer@git.edu.gh',
    firstName: 'Frank',
    lastName: 'Amponsah',
    middleName: 'Yaw',
    title: 'Dr',
    role: 'LECTURER',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-30-555-1301',
    dateOfBirth: new Date('1976-07-11'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '357 Electric Avenue, Accra',
    facultyCode: 'ENG',
    departmentCode: 'EEE'
  },

  // Students - Computer Science
  {
    email: 'alice.student@st.git.edu.gh',
    firstName: 'Alice',
    lastName: 'Owusu',
    middleName: 'Akosua',
    title: null,
    role: 'STUDENT',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-24-555-2001',
    dateOfBirth: new Date('2003-05-15'),
    gender: 'Female',
    nationality: 'Ghanaian',
    address: '12 Student Hostel Block A, GIT Campus',
    facultyCode: 'ENG',
    departmentCode: 'CSE'
  },
  {
    email: 'bob.student@st.git.edu.gh',
    firstName: 'Bob',
    lastName: 'Agyeman',
    middleName: 'Kwame',
    title: null,
    role: 'STUDENT',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-24-555-2002',
    dateOfBirth: new Date('2002-08-22'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '15 Student Hostel Block B, GIT Campus',
    facultyCode: 'ENG',
    departmentCode: 'CSE'
  },
  {
    email: 'clara.student@st.git.edu.gh',
    firstName: 'Clara',
    lastName: 'Asiedu',
    middleName: 'Ama',
    title: null,
    role: 'STUDENT',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-24-555-2003',
    dateOfBirth: new Date('2003-11-08'),
    gender: 'Female',
    nationality: 'Ghanaian',
    address: '18 Student Hostel Block C, GIT Campus',
    facultyCode: 'ENG',
    departmentCode: 'CSE'
  },
  {
    email: 'daniel.student@st.git.edu.gh',
    firstName: 'Daniel',
    lastName: 'Nkrumah',
    middleName: 'Kofi',
    title: null,
    role: 'STUDENT',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-24-555-2004',
    dateOfBirth: new Date('2002-12-03'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '21 Student Hostel Block D, GIT Campus',
    facultyCode: 'ENG',
    departmentCode: 'CSE'
  },
  {
    email: 'emma.student@st.git.edu.gh',
    firstName: 'Emma',
    lastName: 'Ofosu',
    middleName: 'Adjoa',
    title: null,
    role: 'STUDENT',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-24-555-2005',
    dateOfBirth: new Date('2003-04-17'),
    gender: 'Female',
    nationality: 'Ghanaian',
    address: '24 Student Hostel Block E, GIT Campus',
    facultyCode: 'ENG',
    departmentCode: 'CSE'
  },

  // Students - Mathematics
  {
    email: 'frank.student@st.git.edu.gh',
    firstName: 'Frank',
    lastName: 'Boakye',
    middleName: 'Yaw',
    title: null,
    role: 'STUDENT',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-24-555-2101',
    dateOfBirth: new Date('2003-01-25'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '31 Student Hostel Block F, GIT Campus',
    facultyCode: 'SCI',
    departmentCode: 'MATH'
  },
  {
    email: 'grace.student@st.git.edu.gh',
    firstName: 'Grace',
    lastName: 'Appiah',
    middleName: 'Akosua',
    title: null,
    role: 'STUDENT',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-24-555-2102',
    dateOfBirth: new Date('2002-09-14'),
    gender: 'Female',
    nationality: 'Ghanaian',
    address: '34 Student Hostel Block G, GIT Campus',
    facultyCode: 'SCI',
    departmentCode: 'MATH'
  },
  {
    email: 'henry.student@st.git.edu.gh',
    firstName: 'Henry',
    lastName: 'Mensah',
    middleName: 'Kwaku',
    title: null,
    role: 'STUDENT',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-24-555-2103',
    dateOfBirth: new Date('2003-06-07'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '37 Student Hostel Block H, GIT Campus',
    facultyCode: 'SCI',
    departmentCode: 'MATH'
  },

  // Students - Physics
  {
    email: 'irene.student@st.git.edu.gh',
    firstName: 'Irene',
    lastName: 'Agyei',
    middleName: 'Ama',
    title: null,
    role: 'STUDENT',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-24-555-2201',
    dateOfBirth: new Date('2002-10-20'),
    gender: 'Female',
    nationality: 'Ghanaian',
    address: '41 Student Hostel Block I, GIT Campus',
    facultyCode: 'SCI',
    departmentCode: 'PHYS'
  },
  {
    email: 'john.student@st.git.edu.gh',
    firstName: 'John',
    lastName: 'Opoku',
    middleName: 'Kofi',
    title: null,
    role: 'STUDENT',
    status: 'ACTIVE',
    emailVerified: true,
    phone: '+233-24-555-2202',
    dateOfBirth: new Date('2003-03-12'),
    gender: 'Male',
    nationality: 'Ghanaian',
    address: '44 Student Hostel Block J, GIT Campus',
    facultyCode: 'SCI',
    departmentCode: 'PHYS'
  }
];

// Additional user profiles data
export const lecturerProfilesData = [
  {
    email: 'james.lecturer@git.edu.gh',
    staffId: 'GIT-CSE-001',
    academicRank: 'LECTURER',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    hireDate: new Date('2020-09-01'),
    highestQualification: 'PhD in Computer Science',
    specialization: 'Software Engineering and Database Systems',
    permissions: {
      canCreateExams: true,
      canGradeScripts: true,
      canViewResults: true,
      canManageCourses: true
    }
  },
  {
    email: 'jennifer.lecturer@git.edu.gh',
    staffId: 'GIT-CSE-002',
    academicRank: 'LECTURER',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    hireDate: new Date('2019-01-15'),
    highestQualification: 'PhD in Computer Science',
    specialization: 'Artificial Intelligence and Machine Learning',
    permissions: {
      canCreateExams: true,
      canGradeScripts: true,
      canViewResults: true,
      canManageCourses: true
    }
  },
  {
    email: 'peter.lecturer@git.edu.gh',
    staffId: 'GIT-CSE-003',
    academicRank: 'SENIOR_LECTURER',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    hireDate: new Date('2015-08-01'),
    highestQualification: 'PhD in Computer Science',
    specialization: 'Data Structures and Algorithms',
    permissions: {
      canCreateExams: true,
      canGradeScripts: true,
      canViewResults: true,
      canManageCourses: true
    }
  },
  {
    email: 'elizabeth.lecturer@git.edu.gh',
    staffId: 'GIT-MATH-001',
    academicRank: 'LECTURER',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    hireDate: new Date('2021-02-01'),
    highestQualification: 'PhD in Applied Mathematics',
    specialization: 'Numerical Analysis and Statistics',
    permissions: {
      canCreateExams: true,
      canGradeScripts: true,
      canViewResults: true,
      canManageCourses: true
    }
  },
  {
    email: 'samuel.lecturer@git.edu.gh',
    staffId: 'GIT-MATH-002',
    academicRank: 'SENIOR_LECTURER',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    hireDate: new Date('2017-09-01'),
    highestQualification: 'PhD in Pure Mathematics',
    specialization: 'Abstract Algebra and Discrete Mathematics',
    permissions: {
      canCreateExams: true,
      canGradeScripts: true,
      canViewResults: true,
      canManageCourses: true
    }
  },
  {
    email: 'rachel.lecturer@git.edu.gh',
    staffId: 'GIT-PHYS-001',
    academicRank: 'LECTURER',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    hireDate: new Date('2020-01-15'),
    highestQualification: 'PhD in Physics',
    specialization: 'Condensed Matter Physics',
    permissions: {
      canCreateExams: true,
      canGradeScripts: true,
      canViewResults: true,
      canManageCourses: true
    }
  },
  {
    email: 'frank.lecturer@git.edu.gh',
    staffId: 'GIT-EEE-001',
    academicRank: 'SENIOR_LECTURER',
    employmentType: 'FULL_TIME',
    employmentStatus: 'ACTIVE',
    hireDate: new Date('2016-08-01'),
    highestQualification: 'PhD in Electrical Engineering',
    specialization: 'Power Systems and Control Engineering',
    permissions: {
      canCreateExams: true,
      canGradeScripts: true,
      canViewResults: true,
      canManageCourses: true
    }
  }
];

export const studentProfilesData = [
  {
    email: 'alice.student@st.git.edu.gh',
    studentId: '10240001',
    indexNumber: 'GIT/CSE/24/001',
    level: 200,
    semester: 1,
    academicYear: '2024/2025',
    admissionDate: new Date('2023-09-01'),
    expectedGraduation: new Date('2027-06-30'),
    enrollmentStatus: 'ACTIVE',
    academicStatus: 'GOOD_STANDING',
    programCode: 'BSC_CS'
  },
  {
    email: 'bob.student@st.git.edu.gh',
    studentId: '10240002',
    indexNumber: 'GIT/CSE/24/002',
    level: 200,
    semester: 1,
    academicYear: '2024/2025',
    admissionDate: new Date('2023-09-01'),
    expectedGraduation: new Date('2027-06-30'),
    enrollmentStatus: 'ACTIVE',
    academicStatus: 'GOOD_STANDING',
    programCode: 'BSC_CS'
  },
  {
    email: 'clara.student@st.git.edu.gh',
    studentId: '10240003',
    indexNumber: 'GIT/CSE/24/003',
    level: 100,
    semester: 1,
    academicYear: '2024/2025',
    admissionDate: new Date('2024-09-01'),
    expectedGraduation: new Date('2028-06-30'),
    enrollmentStatus: 'ACTIVE',
    academicStatus: 'GOOD_STANDING',
    programCode: 'BSC_SE'
  },
  {
    email: 'daniel.student@st.git.edu.gh',
    studentId: '10240004',
    indexNumber: 'GIT/CSE/24/004',
    level: 200,
    semester: 1,
    academicYear: '2024/2025',
    admissionDate: new Date('2023-09-01'),
    expectedGraduation: new Date('2027-06-30'),
    enrollmentStatus: 'ACTIVE',
    academicStatus: 'GOOD_STANDING',
    programCode: 'BSC_CS'
  },
  {
    email: 'emma.student@st.git.edu.gh',
    studentId: '10240005',
    indexNumber: 'GIT/CSE/24/005',
    level: 100,
    semester: 1,
    academicYear: '2024/2025',
    admissionDate: new Date('2024-09-01'),
    expectedGraduation: new Date('2028-06-30'),
    enrollmentStatus: 'ACTIVE',
    academicStatus: 'GOOD_STANDING',
    programCode: 'BSC_SE'
  },
  {
    email: 'frank.student@st.git.edu.gh',
    studentId: '10240101',
    indexNumber: 'GIT/MATH/24/001',
    level: 200,
    semester: 1,
    academicYear: '2024/2025',
    admissionDate: new Date('2023-09-01'),
    expectedGraduation: new Date('2026-06-30'),
    enrollmentStatus: 'ACTIVE',
    academicStatus: 'GOOD_STANDING',
    programCode: 'BSC_MATH'
  },
  {
    email: 'grace.student@st.git.edu.gh',
    studentId: '10240102',
    indexNumber: 'GIT/MATH/24/002',
    level: 200,
    semester: 1,
    academicYear: '2024/2025',
    admissionDate: new Date('2023-09-01'),
    expectedGraduation: new Date('2026-06-30'),
    enrollmentStatus: 'ACTIVE',
    academicStatus: 'GOOD_STANDING',
    programCode: 'BSC_STAT'
  },
  {
    email: 'henry.student@st.git.edu.gh',
    studentId: '10240103',
    indexNumber: 'GIT/MATH/24/003',
    level: 100,
    semester: 1,
    academicYear: '2024/2025',
    admissionDate: new Date('2024-09-01'),
    expectedGraduation: new Date('2027-06-30'),
    enrollmentStatus: 'ACTIVE',
    academicStatus: 'GOOD_STANDING',
    programCode: 'BSC_MATH'
  },
  {
    email: 'irene.student@st.git.edu.gh',
    studentId: '10240201',
    indexNumber: 'GIT/PHYS/24/001',
    level: 200,
    semester: 1,
    academicYear: '2024/2025',
    admissionDate: new Date('2023-09-01'),
    expectedGraduation: new Date('2026-06-30'),
    enrollmentStatus: 'ACTIVE',
    academicStatus: 'GOOD_STANDING',
    programCode: 'BSC_PHYS'
  },
  {
    email: 'john.student@st.git.edu.gh',
    studentId: '10240202',
    indexNumber: 'GIT/PHYS/24/002',
    level: 100,
    semester: 1,
    academicYear: '2024/2025',
    admissionDate: new Date('2024-09-01'),
    expectedGraduation: new Date('2027-06-30'),
    enrollmentStatus: 'ACTIVE',
    academicStatus: 'GOOD_STANDING',
    programCode: 'BSC_PHYS'
  }
];

export default usersData;
